- name: Network AIOPS
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Network Load issue Detected
      condition:
        all:
          - event.sourcetype == "itsi_notable:group"
          - event.severity == "6"
      throttle:
        group_by_attributes:
          - event.payload.service_title     # Corrected field name reference
        once_within: 5 minutes
      action:
        run_workflow_template:
          name: Network Throughput Remediation
          organization: Default
          post_events: true
